name: MODFLOW 6 continuous integration
on:
  push:
    branches:
      - master
      - develop
      - ci-diagnose*
      - PRT
    paths-ignore:
      - '**.md'
      - 'doc/**'
  pull_request:
    branches:
      - master
      - develop
      - PRT
    paths-ignore:
      - '**.md'
      - 'doc/**'
env:
  LABEL: prt
jobs:
  lint:
    name: Lint (fprettify)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Check Fortran source formatting
        run: python .github/common/fortran_format_check.py

  build:
    name: Build and unit test (gfortran 12)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    defaults:
      run:
        shell: bash -l {0}
    env:
      FC: gfortran
      GCC_V: 12
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
      
      - name: Setup gfortran ${{ env.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          init-shell: >-
            bash
            powershell

      - name: Update version
        run: python distribution/update_version.py -v 6.5.0-$LABEL

      - name: Meson setup
        run: meson setup builddir --prefix=$PWD --libdir=bin -Ddebug=false -Dwerror=true

      - name: Meson compile
        run: meson install -C builddir

      - name: Meson test
        run: meson test --verbose --no-rebuild -C builddir

      - name: Move code.json
        run: cp code.json bin/code.json

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: bin-${{ runner.os }}
          path: bin

  smoke_test:
    name: Smoke testing (gfortran 12)
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    env:
      FC: gfortran
      GCC_V: 12
    steps:
      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Setup GNU Fortran ${{ env.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Build modflow6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir

      - name: Update flopy
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Get executables
        working-directory: modflow6/autotest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0 get_exes.py

      - name: Test programs
        working-directory: modflow6/autotest
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            pytest -v -n auto --durations 0 -m "not slow and not regression and not developmode"
          else
            pytest -v -n auto --durations 0 -S
          fi

  test_gfortran_latest:
    name: Integration testing (gfortran 12)
    needs:
      - lint
      - build
      - smoke_test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
    defaults:
      run:
        shell: bash -l {0}
    env:
      FC: gfortran
      GCC_V: 12
    steps:
      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Checkout modflow6-testmodels
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-testmodels
          path: modflow6-testmodels
      
      - name: Checkout modflow6-examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples
      
      - name: Setup GNU Fortran ${{ env.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          cache-downloads: true

      - name: Build modflow6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir

      - name: Update flopy
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Get executables
        working-directory: modflow6/autotest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pytest -v --durations 0 get_exes.py

      - name: Test modflow6
        working-directory: modflow6/autotest
        env:
          REPOS_PATH: ${{ github.workspace }}
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            pytest -v -n auto --durations 0 -m "not large and not developmode"
          else
            pytest -v -n auto --durations 0 -m "not large"
          fi
      
      # steps below run only on Linux to test distribution procedures, e.g.
      # compiling binaries, building documentation
      - name: Checkout usgslatex
        if: runner.os == 'Linux'
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/usgslatex
          path: usgslatex

      - name: Install TeX Live
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install texlive-science \
            texlive-latex-extra \
            texlive-font-utils \
            texlive-fonts-recommended \
            texlive-fonts-extra

      - name: Install USGS LaTeX style files and Univers font
        if: runner.os == 'Linux'
        working-directory: usgslatex/usgsLaTeX
        run: sudo ./install.sh --all-users
     
      - name: Test distribution scripts
        working-directory: modflow6/distribution
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0

  test_gfortran_previous:
    name: Integration testing gfortran (${{ matrix.GCC_V }}, ${{ matrix.os }})
    needs:
      - lint
      - build
      - smoke_test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        GCC_V: [ 7, 8, 9, 10, 11 ]
    defaults:
      run:
        shell: bash -l {0}
    env:
      FC: gfortran
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Checkout modflow6-testmodels
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-testmodels
          path: modflow6-testmodels

      - name: Setup GNU Fortran ${{ matrix.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ matrix.GCC_V }}

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          cache-downloads: true
          cache-environment: true

      - name: Update flopy
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Build modflow6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir
      
      - name: Get executables
        working-directory: modflow6/autotest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0 get_exes.py

      - name: Test modflow6
        working-directory: modflow6/autotest
        env:
          REPOS_PATH: ${{ github.workspace }}
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            pytest -v -n auto --durations 0 -m "not large and not developmode"
          else
            pytest -v -n auto --durations 0 -m "not large"
          fi

  test_ifort:
    name: Integration testing (ifort)
    needs:
      - lint
      - build
      - smoke_test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Checkout modflow6-testmodels
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-testmodels
          path: modflow6-testmodels

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          cache-downloads: true

      - name: Setup Intel Fortran
        uses: modflowpy/install-intelfortran-action@v1

      - name: Update version files
        working-directory: modflow6/distribution
        run: python update_version.py

      - name: Build modflow6
        if: runner.os != 'Windows'
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir

      - name: Build modflow6 (Windows)
        if: runner.os == 'Windows'
        working-directory: modflow6
        shell: pwsh
        run: |
          meson setup builddir -Ddebug=false --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir

      - name: Update flopy
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Get executables
        if: runner.os != 'Windows'
        working-directory: modflow6/autotest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0 get_exes.py
          
      - name: Get executables (Windows)
        if: runner.os == 'Windows'
        working-directory: modflow6/autotest
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0 get_exes.py

      - name: Test programs
        if: runner.os != 'Windows'
        working-directory: modflow6/autotest
        env:
          REPOS_PATH: ${{ github.workspace }}
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            pytest -v -n auto --durations 0 -m "not large and not developmode"
          else
            pytest -v -n auto --durations 0 -m "not large"
          fi

      - name: Test programs (Windows)
        if: runner.os == 'Windows'
        working-directory: modflow6/autotest
        shell: pwsh
        env:
          REPOS_PATH: ${{ github.workspace }}
        run: |
          if ( "${{ github.ref_name }}" -eq "master" ) {
            pytest -v -n auto --durations 0 -m "not large and not developmode"
          } else {
            pytest -v -n auto --durations 0 -m "not large"
          }

      - name: Test scripts
        if: runner.os != 'Windows'
        working-directory: modflow6/distribution
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0

      - name: Test scripts (Windows)
        if: runner.os == 'Windows'
        working-directory: modflow6/distribution
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0
        
  parallel_test:
    name: Parallel testing
    needs:
      - lint
      - build
      - smoke_test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12 ] #, windows-2022 ]
    defaults:
      run:
        shell: bash -l {0}
    env:
      FC: gfortran
      GCC_V: 12
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          path: modflow6

      - name: Setup MSYS2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-pytest

      - name: Setup MPI
        if: runner.os == 'Windows'
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: msmpi

      - name: Setup GNU Fortran ${{ env.GCC_V }}
        uses: awvwgk/setup-fortran@main
        with:
          compiler: gcc
          version: ${{ env.GCC_V }}

      - name: Cache PETSc
        id: cache-petsc
        uses: actions/cache@v3
        with:
          path: petsc
          key: ${{ runner.os }}-petsc

      - name: Clone PETSc
        if: runner.os != 'Windows' && steps.cache-petsc.outputs.cache-hit != 'true'
        run: git clone -b release https://gitlab.com/petsc/petsc.git petsc

      - name: Download PETSc
        if: runner.os == 'Windows'
        run: |
          curl https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.4.tar.gz -O -J
          mkdir petsc
          tar -xzf petsc-3.18.4.tar.gz -C petsc --strip-components=1

      - name: Configure environment
        if: runner.os == 'Linux'
        run: |
          echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/petsc/linux-gnu/lib/pkgconfig" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/petsc/linux-gnu/bin" >> $GITHUB_PATH

      - name: Configure environment
        if: runner.os == 'macOS'
        run: |
          echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/petsc/arch-darwin-gcc-debug/lib/pkgconfig" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/petsc/arch-darwin-gcc-debug/bin" >> $GITHUB_PATH

      - name: Configure PETSc
        if: runner.os == 'Linux'
        working-directory: petsc
        run: |
          sudo ./configure PETSC_ARCH=linux-gnu --download-fblaslapack --download-openmpi
          sudo make all

      - name: Configure PETSc
        if: runner.os == 'macOS'
        working-directory: petsc
        run: |
          sudo ./configure PETSC_DIR="$GITHUB_WORKSPACE/petsc" PETSC_ARCH=arch-darwin-gcc-debug --download-fblaslapack --download-openmpi
          sudo make all

      - name: Configure PETSc
        if: runner.os == 'Windows'
        shell: msys2 {0}
        working-directory: petsc
        run: |
          pacman -Syu
          pacman -Sy --noconfirm autoconf automake-wrapper bison bsdcpio make git \
            mingw-w64-x86_64-toolchain patch python flex \
            pkg-config pkgfile tar unzip mingw-w64-x86_64-cmake \
            mingw-w64-x86_64-msmpi mingw-w64-x86_64-openblas mingw-w64-x86_64-jq
          /usr/bin/python ./configure --with-mpiexec='/C/Program\ Files/Microsoft\ MPI/Bin/mpiexec' --with-shared-libraries=0
          make all

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          cache-downloads: true

      - name: Build modflow6
        working-directory: modflow6
        run: |
          meson setup builddir -Ddebug=false -Dparallel=true --prefix=$(pwd) --libdir=bin
          meson install -C builddir
          meson test --verbose --no-rebuild -C builddir

      - name: Show Meson logs
        if: failure()
        working-directory: modflow6
        run: cat builddir/meson-logs/meson-log.txt

      - name: Update flopy
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Get executables
        working-directory: modflow6/autotest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: pytest -v --durations 0 get_exes.py

      - name: Test programs (parallel)
        working-directory: modflow6/autotest
        env:
          REPOS_PATH: ${{ github.workspace }}
        run: |
          branch="${{ github.ref_name }}"
          marker="not large"
          markers=$([ "$branch" == "master" ] && echo "$marker and not developmode" || echo "$marker")
          pytest -v -n auto --parallel --durations 0 -m "$markers"
          
  docs:
    name: Build documentation
    needs: build
    if: github.ref_name == 'PRT'
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: aprovost-usgs/modflow6
          path: modflow6
          ref: PRT

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Checkout usgslatex
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/usgslatex
          path: usgslatex

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt install texlive-latex-extra \
            texlive-science \
            texlive-font-utils \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            dos2unix

      - name: Install USGS LaTeX style files and Univers font
        working-directory: usgslatex/usgsLaTeX
        run: sudo ./install.sh --all-users

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: bin-${{ runner.os }}
          path: modflow6/bin

      - name: Checkout modflow6-examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples

      - name: Cache modflow6 examples
        id: cache-examples
        uses: actions/cache@v3
        with:
          path: modflow6-examples/examples
          key: modflow6-examples-${{ hashFiles('modflow6-examples/scripts/**') }}

      - name: Install extra Python packages
        if: steps.cache-examples.outputs.cache-hit != 'true'
        working-directory: modflow6-examples/etc
        run: pip install -r requirements.pip.txt

      - name: Build example models
        if: steps.cache-examples.outputs.cache-hit != 'true'
        working-directory: modflow6-examples/etc
        run: python ci_build_files.py

      - name: Update version
        run: python modflow6/distribution/update_version.py -v 6.5.0-$LABEL

      - name: Build docs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # example path below is hard-coded into modflow6/distribution/build_docs.py
          # once that's fixed, this can be removed
          mkdir -p modflow6-examples/examples/ex-gwf-twri01
          
          # execute permission may not have survived upload/download-artifact actions
          chmod +x modflow6/bin/mf6
          chmod +x modflow6/bin/mf5to6
          chmod +x modflow6/bin/zbud6
          
          # build the docs
          python modflow6/distribution/build_docs.py -d -b modflow6/bin -o docs

      - name: Upload mf6io docs
        uses: actions/upload-artifact@v3
        with:
          name: mf6io
          path: docs/mf6io.pdf
      
      - name: Upload release notes
        uses: actions/upload-artifact@v3
        with:
          name: ReleaseNotes
          path: docs/ReleaseNotes.pdf

  dist:
    name: Build distributions
    needs: docs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            artifact_name: linux
          - os: macos-12
            artifact_name: mac
          - os: windows-2022
            artifact_name: win64
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout modflow6
        uses: actions/checkout@v3
        with:
          repository: aprovost-usgs/modflow6
          path: modflow6
          ref: PRT

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: modflow6/environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Setup Intel Fortran
        uses: modflowpy/install-intelfortran-action@v1

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: bin-${{ runner.os }}
          path: ${{ matrix.artifact_name }}/bin

      - name: Update FloPy classes
        working-directory: modflow6/autotest
        run: python update_flopy.py

      - name: Checkout modflow6-examples
        uses: actions/checkout@v3
        with:
          repository: MODFLOW-USGS/modflow6-examples
          path: modflow6-examples

      - name: Cache modflow6 examples
        id: cache-examples
        uses: actions/cache@v3
        with:
          path: modflow6-examples/examples
          key: modflow6-examples-${{ hashFiles('modflow6-examples/scripts/**') }}

      - name: Install extra Python packages
        if: steps.cache-examples.outputs.cache-hit != 'true'
        working-directory: modflow6-examples/etc
        run: pip install -r requirements.pip.txt

      - name: Build example models
        if: steps.cache-examples.outputs.cache-hit != 'true'
        working-directory: modflow6-examples/etc
        run: python ci_build_files.py

      - name: Build distribution
        run: |
          # modflow6/distribution/build_dist.py expects the examples repo to exist,
          # but it's not needed for nightly builds, below can be removed when fixed
          mkdir -p modflow6-examples
          
          # build the dist
          python modflow6/distribution/build_dist.py -d -o ${{ matrix.artifact_name }}

      - name: Zip distribution
        if: runner.os != 'Windows'
        run: zip -j -r ${{ matrix.artifact_name }}.zip ${{ matrix.artifact_name }} -x '*.DS_Store'

      - name: Zip distribution (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: 7z a -tzip ${{ matrix.artifact_name }}.zip ${{ github.workspace }}\${{ matrix.artifact_name }}\bin\* -xr'!libmf6.lib'

      - name: Upload distribution
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.zip

      - name: Upload mf6io docs
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: mf6io
          path: ${{ matrix.artifact_name }}/doc/mf6io.pdf

  release:
    name: Create release
    needs: dist
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    if:
      github.event_name == 'push' || github.event_name == 'schedule'
    steps:

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 30
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: nightly

      - name: List files in the artifact directory
        run: ls -l nightly

      - name: Get time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD

      - name: Show time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $TIME $F_TIME

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.current-time.outputs.formattedTime }}
          name: ${{ steps.current-time.outputs.formattedTime }} nightly build
          body: "MODFLOW 6 PRT nightly development build, compiled with Intel Fortran."
          draft: false
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      # remove all but zip and pdf files
      - name: Prune release assets
        run: find nightly -type f ! -name '*.zip' ! -name '*.pdf' -delete

      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: nightly/**
          tag: ${{ steps.current-time.outputs.formattedTime }}
          overwrite: true
          file_glob: true
